// <auto-generated />
using System;
using MantIA.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MantIA.DAL.Migrations
{
    [DbContext(typeof(MantIADbContext))]
    [Migration("20260629215123_AddNivelPermisoAUsuario")]
    partial class AddNivelPermisoAUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MantIA.BE.Entities.CatalogoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EstadoEnriquecimiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_enriquecimiento");

                    b.Property<string>("FallasComunes")
                        .HasColumnType("text")
                        .HasColumnName("fallas_comunes");

                    b.Property<DateTime?>("FechaUltimoEnriquecimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_enriquecimiento");

                    b.Property<string>("IntervalosMantenimiento")
                        .HasColumnType("text")
                        .HasColumnName("intervalos_mantenimiento");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("RepuestosSugeridos")
                        .HasColumnType("text")
                        .HasColumnName("repuestos_sugeridos");

                    b.HasKey("Id")
                        .HasName("pk_catalogos_maquina");

                    b.ToTable("catalogos_maquina", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dominio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<int>("MaxMaquinasHabilitadas")
                        .HasColumnType("integer")
                        .HasColumnName("max_maquinas_habilitadas");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogoMaquinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_maquina_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("text")
                        .HasColumnName("numero_serie");

                    b.Property<Guid?>("PlantaId")
                        .HasColumnType("uuid")
                        .HasColumnName("planta_id");

                    b.HasKey("Id")
                        .HasName("pk_maquinas");

                    b.HasIndex("CatalogoMaquinaId")
                        .HasDatabaseName("ix_maquinas_catalogo_maquina_id");

                    b.ToTable("maquinas", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.NivelPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_niveles_permiso");

                    b.ToTable("niveles_permiso", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.PermisoPorRolYNivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccionPermitida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion_permitida");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid?>("NivelPermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nivel_permiso_id");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurso");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_permisos_por_rol_y_nivel");

                    b.HasIndex("NivelPermisoId")
                        .HasDatabaseName("ix_permisos_por_rol_y_nivel_nivel_permiso_id");

                    b.ToTable("permisos_por_rol_y_nivel", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<Guid?>("NivelPermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("nivel_permiso_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NivelPermisoId")
                        .HasDatabaseName("ix_usuarios_nivel_permiso_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("MantIA.BE.Entities.Maquina", b =>
                {
                    b.HasOne("MantIA.BE.Entities.CatalogoMaquina", "CatalogoMaquina")
                        .WithMany()
                        .HasForeignKey("CatalogoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maquinas_catalogos_maquina_catalogo_maquina_id");

                    b.Navigation("CatalogoMaquina");
                });

            modelBuilder.Entity("MantIA.BE.Entities.PermisoPorRolYNivel", b =>
                {
                    b.HasOne("MantIA.BE.Entities.NivelPermiso", "NivelPermiso")
                        .WithMany()
                        .HasForeignKey("NivelPermisoId")
                        .HasConstraintName("fk_permisos_por_rol_y_nivel_niveles_permiso_nivel_permiso_id");

                    b.Navigation("NivelPermiso");
                });

            modelBuilder.Entity("MantIA.BE.Entities.Usuario", b =>
                {
                    b.HasOne("MantIA.BE.Entities.NivelPermiso", "NivelPermiso")
                        .WithMany()
                        .HasForeignKey("NivelPermisoId")
                        .HasConstraintName("fk_usuarios_niveles_permiso_nivel_permiso_id");

                    b.Navigation("NivelPermiso");
                });
#pragma warning restore 612, 618
        }
    }
}
